
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\POLICIES\SKYPE\PHONE" /v DisableVersionCheck /t REG_DWORD /d 0 /f


reg add "HKEY_LOCAL_MACHINE\SOFTWARE\POLICIES\SKYPE\PHONE" /v DisableFileTransfer/t REG_DWORD /d 1 /f


reg add "HKEY_LOCAL_MACHINE\SOFTWARE\POLICIES\SKYPE\PHONE" /v DisableScreenSharing/t REG_DWORD /d 1 /f


reg add "HKEY_LOCAL_MACHINE\SOFTWARE\POLICIES\SKYPE\PHONE" /v DisableApi/t REG_DWORD /d 1 /f


reg add "HKEY_LOCAL_MACHINE\SOFTWARE\POLICIES\SKYPE\PHONE" /v MemoryOnly/t REG_DWORD /d 1 /f


reg add "HKEY_LOCAL_MACHINE\SOFTWARE\POLICIES\SKYPE\PHONE" /v DisableTCPListen/t REG_DWORD /d 1 /f


reg add "HKEY_LOCAL_MACHINE\SOFTWARE\POLICIES\SKYPE\PHONE" /v DisableSupernode/t REG_DWORD /d 1 /f



